/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PopupsIndexRouteImport } from './routes/popups/index'
import { Route as FormsIndexRouteImport } from './routes/forms/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as PayPublicIdRouteImport } from './routes/pay/$publicId'
import { Route as FormsPaymentReturnRouteImport } from './routes/forms/payment-return'
import { Route as FormsNewRouteImport } from './routes/forms/new'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as DashboardPaymentLinksRouteImport } from './routes/dashboard/payment-links'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardPopupsIndexRouteImport } from './routes/dashboard/popups/index'
import { Route as PopupsPublicIdPreviewRouteImport } from './routes/popups/$publicId/preview'
import { Route as PopupsPublicIdEmbedRouteImport } from './routes/popups/$publicId/embed'
import { Route as PopupsPopupIdEditRouteImport } from './routes/popups/$popupId/edit'
import { Route as PayPublicIdSuccessRouteImport } from './routes/pay/$publicId/success'
import { Route as IntegrationsGoogleCallbackRouteImport } from './routes/integrations/google/callback'
import { Route as FormsSubmitFormIdRouteImport } from './routes/forms/submit/$formId'
import { Route as FormsEmbedFormIdRouteImport } from './routes/forms/embed/$formId'
import { Route as FormsFormIdSubmissionsRouteImport } from './routes/forms/$formId/submissions'
import { Route as FormsFormIdPaymentsRouteImport } from './routes/forms/$formId/payments'
import { Route as FormsFormIdInvoicingRouteImport } from './routes/forms/$formId/invoicing'
import { Route as FormsFormIdFlowRouteImport } from './routes/forms/$formId/flow'
import { Route as FormsFormIdEmailsRouteImport } from './routes/forms/$formId/emails'
import { Route as FormsFormIdEditRouteImport } from './routes/forms/$formId/edit'
import { Route as FormsFormIdDiscountsRouteImport } from './routes/forms/$formId/discounts'
import { Route as FlowExecutionIdCompleteRouteImport } from './routes/flow/$executionId/complete'
import { Route as DashboardPopupsPopupIdRouteImport } from './routes/dashboard/popups/$popupId'
import { Route as ApiInternalReconcilePaymentsRouteImport } from './routes/api/internal/reconcile-payments'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksXenditEndpointKeyRouteImport } from './routes/api/webhooks/xendit/$endpointKey'
import { Route as ApiPopupsPublicIdViewRouteImport } from './routes/api/popups/$publicId/view'
import { Route as ApiPopupsPublicIdConfigRouteImport } from './routes/api/popups/$publicId/config'
import { Route as ApiPopupsPublicIdClickRouteImport } from './routes/api/popups/$publicId/click'
import { Route as ApiFormsFormIdSubmissionsExportRouteImport } from './routes/api/forms/$formId/submissions-export'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PopupsIndexRoute = PopupsIndexRouteImport.update({
  id: '/popups/',
  path: '/popups/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PayPublicIdRoute = PayPublicIdRouteImport.update({
  id: '/pay/$publicId',
  path: '/pay/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsPaymentReturnRoute = FormsPaymentReturnRouteImport.update({
  id: '/forms/payment-return',
  path: '/forms/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentLinksRoute = DashboardPaymentLinksRouteImport.update({
  id: '/dashboard/payment-links',
  path: '/dashboard/payment-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPopupsIndexRoute = DashboardPopupsIndexRouteImport.update({
  id: '/dashboard/popups/',
  path: '/dashboard/popups/',
  getParentRoute: () => rootRouteImport,
} as any)
const PopupsPublicIdPreviewRoute = PopupsPublicIdPreviewRouteImport.update({
  id: '/popups/$publicId/preview',
  path: '/popups/$publicId/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PopupsPublicIdEmbedRoute = PopupsPublicIdEmbedRouteImport.update({
  id: '/popups/$publicId/embed',
  path: '/popups/$publicId/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const PopupsPopupIdEditRoute = PopupsPopupIdEditRouteImport.update({
  id: '/popups/$popupId/edit',
  path: '/popups/$popupId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PayPublicIdSuccessRoute = PayPublicIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PayPublicIdRoute,
} as any)
const IntegrationsGoogleCallbackRoute =
  IntegrationsGoogleCallbackRouteImport.update({
    id: '/integrations/google/callback',
    path: '/integrations/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormsSubmitFormIdRoute = FormsSubmitFormIdRouteImport.update({
  id: '/forms/submit/$formId',
  path: '/forms/submit/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsEmbedFormIdRoute = FormsEmbedFormIdRouteImport.update({
  id: '/forms/embed/$formId',
  path: '/forms/embed/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdSubmissionsRoute = FormsFormIdSubmissionsRouteImport.update({
  id: '/forms/$formId/submissions',
  path: '/forms/$formId/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdPaymentsRoute = FormsFormIdPaymentsRouteImport.update({
  id: '/forms/$formId/payments',
  path: '/forms/$formId/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdInvoicingRoute = FormsFormIdInvoicingRouteImport.update({
  id: '/forms/$formId/invoicing',
  path: '/forms/$formId/invoicing',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdFlowRoute = FormsFormIdFlowRouteImport.update({
  id: '/forms/$formId/flow',
  path: '/forms/$formId/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdEmailsRoute = FormsFormIdEmailsRouteImport.update({
  id: '/forms/$formId/emails',
  path: '/forms/$formId/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdEditRoute = FormsFormIdEditRouteImport.update({
  id: '/forms/$formId/edit',
  path: '/forms/$formId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdDiscountsRoute = FormsFormIdDiscountsRouteImport.update({
  id: '/forms/$formId/discounts',
  path: '/forms/$formId/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowExecutionIdCompleteRoute = FlowExecutionIdCompleteRouteImport.update({
  id: '/flow/$executionId/complete',
  path: '/flow/$executionId/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPopupsPopupIdRoute = DashboardPopupsPopupIdRouteImport.update({
  id: '/dashboard/popups/$popupId',
  path: '/dashboard/popups/$popupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalReconcilePaymentsRoute =
  ApiInternalReconcilePaymentsRouteImport.update({
    id: '/api/internal/reconcile-payments',
    path: '/api/internal/reconcile-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksXenditEndpointKeyRoute =
  ApiWebhooksXenditEndpointKeyRouteImport.update({
    id: '/api/webhooks/xendit/$endpointKey',
    path: '/api/webhooks/xendit/$endpointKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPopupsPublicIdViewRoute = ApiPopupsPublicIdViewRouteImport.update({
  id: '/api/popups/$publicId/view',
  path: '/api/popups/$publicId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPopupsPublicIdConfigRoute = ApiPopupsPublicIdConfigRouteImport.update({
  id: '/api/popups/$publicId/config',
  path: '/api/popups/$publicId/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPopupsPublicIdClickRoute = ApiPopupsPublicIdClickRouteImport.update({
  id: '/api/popups/$publicId/click',
  path: '/api/popups/$publicId/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsFormIdSubmissionsExportRoute =
  ApiFormsFormIdSubmissionsExportRouteImport.update({
    id: '/api/forms/$formId/submissions-export',
    path: '/api/forms/$formId/submissions-export',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discounts': typeof DiscountsRoute
  '/mcp': typeof McpRoute
  '/progress': typeof ProgressRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/payment-links': typeof DashboardPaymentLinksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/forms/new': typeof FormsNewRoute
  '/forms/payment-return': typeof FormsPaymentReturnRoute
  '/pay/$publicId': typeof PayPublicIdRouteWithChildren
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/popups/': typeof PopupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/reconcile-payments': typeof ApiInternalReconcilePaymentsRoute
  '/dashboard/popups/$popupId': typeof DashboardPopupsPopupIdRoute
  '/flow/$executionId/complete': typeof FlowExecutionIdCompleteRoute
  '/forms/$formId/discounts': typeof FormsFormIdDiscountsRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/emails': typeof FormsFormIdEmailsRoute
  '/forms/$formId/flow': typeof FormsFormIdFlowRoute
  '/forms/$formId/invoicing': typeof FormsFormIdInvoicingRoute
  '/forms/$formId/payments': typeof FormsFormIdPaymentsRoute
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
  '/forms/embed/$formId': typeof FormsEmbedFormIdRoute
  '/forms/submit/$formId': typeof FormsSubmitFormIdRoute
  '/integrations/google/callback': typeof IntegrationsGoogleCallbackRoute
  '/pay/$publicId/success': typeof PayPublicIdSuccessRoute
  '/popups/$popupId/edit': typeof PopupsPopupIdEditRoute
  '/popups/$publicId/embed': typeof PopupsPublicIdEmbedRoute
  '/popups/$publicId/preview': typeof PopupsPublicIdPreviewRoute
  '/dashboard/popups/': typeof DashboardPopupsIndexRoute
  '/api/forms/$formId/submissions-export': typeof ApiFormsFormIdSubmissionsExportRoute
  '/api/popups/$publicId/click': typeof ApiPopupsPublicIdClickRoute
  '/api/popups/$publicId/config': typeof ApiPopupsPublicIdConfigRoute
  '/api/popups/$publicId/view': typeof ApiPopupsPublicIdViewRoute
  '/api/webhooks/xendit/$endpointKey': typeof ApiWebhooksXenditEndpointKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discounts': typeof DiscountsRoute
  '/mcp': typeof McpRoute
  '/progress': typeof ProgressRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/payment-links': typeof DashboardPaymentLinksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/forms/new': typeof FormsNewRoute
  '/forms/payment-return': typeof FormsPaymentReturnRoute
  '/pay/$publicId': typeof PayPublicIdRouteWithChildren
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/forms': typeof FormsIndexRoute
  '/popups': typeof PopupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/reconcile-payments': typeof ApiInternalReconcilePaymentsRoute
  '/dashboard/popups/$popupId': typeof DashboardPopupsPopupIdRoute
  '/flow/$executionId/complete': typeof FlowExecutionIdCompleteRoute
  '/forms/$formId/discounts': typeof FormsFormIdDiscountsRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/emails': typeof FormsFormIdEmailsRoute
  '/forms/$formId/flow': typeof FormsFormIdFlowRoute
  '/forms/$formId/invoicing': typeof FormsFormIdInvoicingRoute
  '/forms/$formId/payments': typeof FormsFormIdPaymentsRoute
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
  '/forms/embed/$formId': typeof FormsEmbedFormIdRoute
  '/forms/submit/$formId': typeof FormsSubmitFormIdRoute
  '/integrations/google/callback': typeof IntegrationsGoogleCallbackRoute
  '/pay/$publicId/success': typeof PayPublicIdSuccessRoute
  '/popups/$popupId/edit': typeof PopupsPopupIdEditRoute
  '/popups/$publicId/embed': typeof PopupsPublicIdEmbedRoute
  '/popups/$publicId/preview': typeof PopupsPublicIdPreviewRoute
  '/dashboard/popups': typeof DashboardPopupsIndexRoute
  '/api/forms/$formId/submissions-export': typeof ApiFormsFormIdSubmissionsExportRoute
  '/api/popups/$publicId/click': typeof ApiPopupsPublicIdClickRoute
  '/api/popups/$publicId/config': typeof ApiPopupsPublicIdConfigRoute
  '/api/popups/$publicId/view': typeof ApiPopupsPublicIdViewRoute
  '/api/webhooks/xendit/$endpointKey': typeof ApiWebhooksXenditEndpointKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discounts': typeof DiscountsRoute
  '/mcp': typeof McpRoute
  '/progress': typeof ProgressRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/payment-links': typeof DashboardPaymentLinksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/forms/new': typeof FormsNewRoute
  '/forms/payment-return': typeof FormsPaymentReturnRoute
  '/pay/$publicId': typeof PayPublicIdRouteWithChildren
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/popups/': typeof PopupsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/reconcile-payments': typeof ApiInternalReconcilePaymentsRoute
  '/dashboard/popups/$popupId': typeof DashboardPopupsPopupIdRoute
  '/flow/$executionId/complete': typeof FlowExecutionIdCompleteRoute
  '/forms/$formId/discounts': typeof FormsFormIdDiscountsRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/emails': typeof FormsFormIdEmailsRoute
  '/forms/$formId/flow': typeof FormsFormIdFlowRoute
  '/forms/$formId/invoicing': typeof FormsFormIdInvoicingRoute
  '/forms/$formId/payments': typeof FormsFormIdPaymentsRoute
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
  '/forms/embed/$formId': typeof FormsEmbedFormIdRoute
  '/forms/submit/$formId': typeof FormsSubmitFormIdRoute
  '/integrations/google/callback': typeof IntegrationsGoogleCallbackRoute
  '/pay/$publicId/success': typeof PayPublicIdSuccessRoute
  '/popups/$popupId/edit': typeof PopupsPopupIdEditRoute
  '/popups/$publicId/embed': typeof PopupsPublicIdEmbedRoute
  '/popups/$publicId/preview': typeof PopupsPublicIdPreviewRoute
  '/dashboard/popups/': typeof DashboardPopupsIndexRoute
  '/api/forms/$formId/submissions-export': typeof ApiFormsFormIdSubmissionsExportRoute
  '/api/popups/$publicId/click': typeof ApiPopupsPublicIdClickRoute
  '/api/popups/$publicId/config': typeof ApiPopupsPublicIdConfigRoute
  '/api/popups/$publicId/view': typeof ApiPopupsPublicIdViewRoute
  '/api/webhooks/xendit/$endpointKey': typeof ApiWebhooksXenditEndpointKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discounts'
    | '/mcp'
    | '/progress'
    | '/sign-in'
    | '/sign-out'
    | '/api/health'
    | '/dashboard/payment-links'
    | '/docs/$slug'
    | '/forms/new'
    | '/forms/payment-return'
    | '/pay/$publicId'
    | '/settings/integrations'
    | '/settings/profile'
    | '/dashboard/'
    | '/docs/'
    | '/forms/'
    | '/popups/'
    | '/api/auth/$'
    | '/api/internal/reconcile-payments'
    | '/dashboard/popups/$popupId'
    | '/flow/$executionId/complete'
    | '/forms/$formId/discounts'
    | '/forms/$formId/edit'
    | '/forms/$formId/emails'
    | '/forms/$formId/flow'
    | '/forms/$formId/invoicing'
    | '/forms/$formId/payments'
    | '/forms/$formId/submissions'
    | '/forms/embed/$formId'
    | '/forms/submit/$formId'
    | '/integrations/google/callback'
    | '/pay/$publicId/success'
    | '/popups/$popupId/edit'
    | '/popups/$publicId/embed'
    | '/popups/$publicId/preview'
    | '/dashboard/popups/'
    | '/api/forms/$formId/submissions-export'
    | '/api/popups/$publicId/click'
    | '/api/popups/$publicId/config'
    | '/api/popups/$publicId/view'
    | '/api/webhooks/xendit/$endpointKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discounts'
    | '/mcp'
    | '/progress'
    | '/sign-in'
    | '/sign-out'
    | '/api/health'
    | '/dashboard/payment-links'
    | '/docs/$slug'
    | '/forms/new'
    | '/forms/payment-return'
    | '/pay/$publicId'
    | '/settings/integrations'
    | '/settings/profile'
    | '/dashboard'
    | '/docs'
    | '/forms'
    | '/popups'
    | '/api/auth/$'
    | '/api/internal/reconcile-payments'
    | '/dashboard/popups/$popupId'
    | '/flow/$executionId/complete'
    | '/forms/$formId/discounts'
    | '/forms/$formId/edit'
    | '/forms/$formId/emails'
    | '/forms/$formId/flow'
    | '/forms/$formId/invoicing'
    | '/forms/$formId/payments'
    | '/forms/$formId/submissions'
    | '/forms/embed/$formId'
    | '/forms/submit/$formId'
    | '/integrations/google/callback'
    | '/pay/$publicId/success'
    | '/popups/$popupId/edit'
    | '/popups/$publicId/embed'
    | '/popups/$publicId/preview'
    | '/dashboard/popups'
    | '/api/forms/$formId/submissions-export'
    | '/api/popups/$publicId/click'
    | '/api/popups/$publicId/config'
    | '/api/popups/$publicId/view'
    | '/api/webhooks/xendit/$endpointKey'
  id:
    | '__root__'
    | '/'
    | '/discounts'
    | '/mcp'
    | '/progress'
    | '/sign-in'
    | '/sign-out'
    | '/api/health'
    | '/dashboard/payment-links'
    | '/docs/$slug'
    | '/forms/new'
    | '/forms/payment-return'
    | '/pay/$publicId'
    | '/settings/integrations'
    | '/settings/profile'
    | '/dashboard/'
    | '/docs/'
    | '/forms/'
    | '/popups/'
    | '/api/auth/$'
    | '/api/internal/reconcile-payments'
    | '/dashboard/popups/$popupId'
    | '/flow/$executionId/complete'
    | '/forms/$formId/discounts'
    | '/forms/$formId/edit'
    | '/forms/$formId/emails'
    | '/forms/$formId/flow'
    | '/forms/$formId/invoicing'
    | '/forms/$formId/payments'
    | '/forms/$formId/submissions'
    | '/forms/embed/$formId'
    | '/forms/submit/$formId'
    | '/integrations/google/callback'
    | '/pay/$publicId/success'
    | '/popups/$popupId/edit'
    | '/popups/$publicId/embed'
    | '/popups/$publicId/preview'
    | '/dashboard/popups/'
    | '/api/forms/$formId/submissions-export'
    | '/api/popups/$publicId/click'
    | '/api/popups/$publicId/config'
    | '/api/popups/$publicId/view'
    | '/api/webhooks/xendit/$endpointKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscountsRoute: typeof DiscountsRoute
  McpRoute: typeof McpRoute
  ProgressRoute: typeof ProgressRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DashboardPaymentLinksRoute: typeof DashboardPaymentLinksRoute
  DocsSlugRoute: typeof DocsSlugRoute
  FormsNewRoute: typeof FormsNewRoute
  FormsPaymentReturnRoute: typeof FormsPaymentReturnRoute
  PayPublicIdRoute: typeof PayPublicIdRouteWithChildren
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  FormsIndexRoute: typeof FormsIndexRoute
  PopupsIndexRoute: typeof PopupsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalReconcilePaymentsRoute: typeof ApiInternalReconcilePaymentsRoute
  DashboardPopupsPopupIdRoute: typeof DashboardPopupsPopupIdRoute
  FlowExecutionIdCompleteRoute: typeof FlowExecutionIdCompleteRoute
  FormsFormIdDiscountsRoute: typeof FormsFormIdDiscountsRoute
  FormsFormIdEditRoute: typeof FormsFormIdEditRoute
  FormsFormIdEmailsRoute: typeof FormsFormIdEmailsRoute
  FormsFormIdFlowRoute: typeof FormsFormIdFlowRoute
  FormsFormIdInvoicingRoute: typeof FormsFormIdInvoicingRoute
  FormsFormIdPaymentsRoute: typeof FormsFormIdPaymentsRoute
  FormsFormIdSubmissionsRoute: typeof FormsFormIdSubmissionsRoute
  FormsEmbedFormIdRoute: typeof FormsEmbedFormIdRoute
  FormsSubmitFormIdRoute: typeof FormsSubmitFormIdRoute
  IntegrationsGoogleCallbackRoute: typeof IntegrationsGoogleCallbackRoute
  PopupsPopupIdEditRoute: typeof PopupsPopupIdEditRoute
  PopupsPublicIdEmbedRoute: typeof PopupsPublicIdEmbedRoute
  PopupsPublicIdPreviewRoute: typeof PopupsPublicIdPreviewRoute
  DashboardPopupsIndexRoute: typeof DashboardPopupsIndexRoute
  ApiFormsFormIdSubmissionsExportRoute: typeof ApiFormsFormIdSubmissionsExportRoute
  ApiPopupsPublicIdClickRoute: typeof ApiPopupsPublicIdClickRoute
  ApiPopupsPublicIdConfigRoute: typeof ApiPopupsPublicIdConfigRoute
  ApiPopupsPublicIdViewRoute: typeof ApiPopupsPublicIdViewRoute
  ApiWebhooksXenditEndpointKeyRoute: typeof ApiWebhooksXenditEndpointKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popups/': {
      id: '/popups/'
      path: '/popups'
      fullPath: '/popups/'
      preLoaderRoute: typeof PopupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$publicId': {
      id: '/pay/$publicId'
      path: '/pay/$publicId'
      fullPath: '/pay/$publicId'
      preLoaderRoute: typeof PayPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/payment-return': {
      id: '/forms/payment-return'
      path: '/forms/payment-return'
      fullPath: '/forms/payment-return'
      preLoaderRoute: typeof FormsPaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payment-links': {
      id: '/dashboard/payment-links'
      path: '/dashboard/payment-links'
      fullPath: '/dashboard/payment-links'
      preLoaderRoute: typeof DashboardPaymentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/popups/': {
      id: '/dashboard/popups/'
      path: '/dashboard/popups'
      fullPath: '/dashboard/popups/'
      preLoaderRoute: typeof DashboardPopupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popups/$publicId/preview': {
      id: '/popups/$publicId/preview'
      path: '/popups/$publicId/preview'
      fullPath: '/popups/$publicId/preview'
      preLoaderRoute: typeof PopupsPublicIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popups/$publicId/embed': {
      id: '/popups/$publicId/embed'
      path: '/popups/$publicId/embed'
      fullPath: '/popups/$publicId/embed'
      preLoaderRoute: typeof PopupsPublicIdEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popups/$popupId/edit': {
      id: '/popups/$popupId/edit'
      path: '/popups/$popupId/edit'
      fullPath: '/popups/$popupId/edit'
      preLoaderRoute: typeof PopupsPopupIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$publicId/success': {
      id: '/pay/$publicId/success'
      path: '/success'
      fullPath: '/pay/$publicId/success'
      preLoaderRoute: typeof PayPublicIdSuccessRouteImport
      parentRoute: typeof PayPublicIdRoute
    }
    '/integrations/google/callback': {
      id: '/integrations/google/callback'
      path: '/integrations/google/callback'
      fullPath: '/integrations/google/callback'
      preLoaderRoute: typeof IntegrationsGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/submit/$formId': {
      id: '/forms/submit/$formId'
      path: '/forms/submit/$formId'
      fullPath: '/forms/submit/$formId'
      preLoaderRoute: typeof FormsSubmitFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/embed/$formId': {
      id: '/forms/embed/$formId'
      path: '/forms/embed/$formId'
      fullPath: '/forms/embed/$formId'
      preLoaderRoute: typeof FormsEmbedFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/submissions': {
      id: '/forms/$formId/submissions'
      path: '/forms/$formId/submissions'
      fullPath: '/forms/$formId/submissions'
      preLoaderRoute: typeof FormsFormIdSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/payments': {
      id: '/forms/$formId/payments'
      path: '/forms/$formId/payments'
      fullPath: '/forms/$formId/payments'
      preLoaderRoute: typeof FormsFormIdPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/invoicing': {
      id: '/forms/$formId/invoicing'
      path: '/forms/$formId/invoicing'
      fullPath: '/forms/$formId/invoicing'
      preLoaderRoute: typeof FormsFormIdInvoicingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/flow': {
      id: '/forms/$formId/flow'
      path: '/forms/$formId/flow'
      fullPath: '/forms/$formId/flow'
      preLoaderRoute: typeof FormsFormIdFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/emails': {
      id: '/forms/$formId/emails'
      path: '/forms/$formId/emails'
      fullPath: '/forms/$formId/emails'
      preLoaderRoute: typeof FormsFormIdEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/edit': {
      id: '/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof FormsFormIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/discounts': {
      id: '/forms/$formId/discounts'
      path: '/forms/$formId/discounts'
      fullPath: '/forms/$formId/discounts'
      preLoaderRoute: typeof FormsFormIdDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/$executionId/complete': {
      id: '/flow/$executionId/complete'
      path: '/flow/$executionId/complete'
      fullPath: '/flow/$executionId/complete'
      preLoaderRoute: typeof FlowExecutionIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/popups/$popupId': {
      id: '/dashboard/popups/$popupId'
      path: '/dashboard/popups/$popupId'
      fullPath: '/dashboard/popups/$popupId'
      preLoaderRoute: typeof DashboardPopupsPopupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/reconcile-payments': {
      id: '/api/internal/reconcile-payments'
      path: '/api/internal/reconcile-payments'
      fullPath: '/api/internal/reconcile-payments'
      preLoaderRoute: typeof ApiInternalReconcilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/xendit/$endpointKey': {
      id: '/api/webhooks/xendit/$endpointKey'
      path: '/api/webhooks/xendit/$endpointKey'
      fullPath: '/api/webhooks/xendit/$endpointKey'
      preLoaderRoute: typeof ApiWebhooksXenditEndpointKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/popups/$publicId/view': {
      id: '/api/popups/$publicId/view'
      path: '/api/popups/$publicId/view'
      fullPath: '/api/popups/$publicId/view'
      preLoaderRoute: typeof ApiPopupsPublicIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/popups/$publicId/config': {
      id: '/api/popups/$publicId/config'
      path: '/api/popups/$publicId/config'
      fullPath: '/api/popups/$publicId/config'
      preLoaderRoute: typeof ApiPopupsPublicIdConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/popups/$publicId/click': {
      id: '/api/popups/$publicId/click'
      path: '/api/popups/$publicId/click'
      fullPath: '/api/popups/$publicId/click'
      preLoaderRoute: typeof ApiPopupsPublicIdClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$formId/submissions-export': {
      id: '/api/forms/$formId/submissions-export'
      path: '/api/forms/$formId/submissions-export'
      fullPath: '/api/forms/$formId/submissions-export'
      preLoaderRoute: typeof ApiFormsFormIdSubmissionsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PayPublicIdRouteChildren {
  PayPublicIdSuccessRoute: typeof PayPublicIdSuccessRoute
}

const PayPublicIdRouteChildren: PayPublicIdRouteChildren = {
  PayPublicIdSuccessRoute: PayPublicIdSuccessRoute,
}

const PayPublicIdRouteWithChildren = PayPublicIdRoute._addFileChildren(
  PayPublicIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscountsRoute: DiscountsRoute,
  McpRoute: McpRoute,
  ProgressRoute: ProgressRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  ApiHealthRoute: ApiHealthRoute,
  DashboardPaymentLinksRoute: DashboardPaymentLinksRoute,
  DocsSlugRoute: DocsSlugRoute,
  FormsNewRoute: FormsNewRoute,
  FormsPaymentReturnRoute: FormsPaymentReturnRoute,
  PayPublicIdRoute: PayPublicIdRouteWithChildren,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  FormsIndexRoute: FormsIndexRoute,
  PopupsIndexRoute: PopupsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalReconcilePaymentsRoute: ApiInternalReconcilePaymentsRoute,
  DashboardPopupsPopupIdRoute: DashboardPopupsPopupIdRoute,
  FlowExecutionIdCompleteRoute: FlowExecutionIdCompleteRoute,
  FormsFormIdDiscountsRoute: FormsFormIdDiscountsRoute,
  FormsFormIdEditRoute: FormsFormIdEditRoute,
  FormsFormIdEmailsRoute: FormsFormIdEmailsRoute,
  FormsFormIdFlowRoute: FormsFormIdFlowRoute,
  FormsFormIdInvoicingRoute: FormsFormIdInvoicingRoute,
  FormsFormIdPaymentsRoute: FormsFormIdPaymentsRoute,
  FormsFormIdSubmissionsRoute: FormsFormIdSubmissionsRoute,
  FormsEmbedFormIdRoute: FormsEmbedFormIdRoute,
  FormsSubmitFormIdRoute: FormsSubmitFormIdRoute,
  IntegrationsGoogleCallbackRoute: IntegrationsGoogleCallbackRoute,
  PopupsPopupIdEditRoute: PopupsPopupIdEditRoute,
  PopupsPublicIdEmbedRoute: PopupsPublicIdEmbedRoute,
  PopupsPublicIdPreviewRoute: PopupsPublicIdPreviewRoute,
  DashboardPopupsIndexRoute: DashboardPopupsIndexRoute,
  ApiFormsFormIdSubmissionsExportRoute: ApiFormsFormIdSubmissionsExportRoute,
  ApiPopupsPublicIdClickRoute: ApiPopupsPublicIdClickRoute,
  ApiPopupsPublicIdConfigRoute: ApiPopupsPublicIdConfigRoute,
  ApiPopupsPublicIdViewRoute: ApiPopupsPublicIdViewRoute,
  ApiWebhooksXenditEndpointKeyRoute: ApiWebhooksXenditEndpointKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
